name: Build and Save Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t retro-snake .

      - name: Archive Image
        run: docker save -o Retro-Snake.tar retro-snake

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: retro-snake-docker-image
          path: Retro-Snake.tar
